name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Android SDK
        uses: https://github.com/android-actions/setup-android@v3
        with:
          packages: 'tools platform-tools platforms;android-37 build-tools;35.0.0'

      - name: Prepare Gradle environment
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Unit tests
        run: ./gradlew test

      - name: Debug build
        run: ./gradlew assembleDebug
